# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


class TestPRO1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
        self.wait = WebDriverWait(self.driver, 10)

    def teardown_method(self, method):
        self.driver.quit()

    def test_pRO1(self):
        self.driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
        self.driver.set_window_size(1254, 662)

        # Wait for username
        self.wait.until(
            EC.visibility_of_element_located((By.NAME, "username"))
        ).send_keys("Admin")

        # Wait for password
        self.wait.until(
            EC.visibility_of_element_located((By.NAME, "password"))
        ).send_keys("admin123")

        # Click login button
        self.wait.until(
            EC.element_to_be_clickable((By.CSS_SELECTOR, ".oxd-button"))
        ).click()

        # Validate successful login (Dashboard)
        self.wait.until(
            EC.visibility_of_element_located((By.XPATH, "//h6[text()='Dashboard']"))
        )
